/**
 * The @nebutra/ui catalog — every component, where it sits, how settled it is,
 * and the demos that show it (ADR 2026-09-27 UI catalog).
 *
 * One list serves every surface: Sailor Studio renders it, the registry
 * serves its demos, and agents search it. Nothing else describes the
 * library, so nothing else can drift from it.
 *
 * Maintained by hand. `catalog.test.ts` holds it to the source tree: every
 * component file belongs to exactly one entry (or to INTERNAL_FILES), every
 * demo in ./demos belongs to exactly one entry and is named after it, and
 * tests/architecture/ui-catalog.test.ts keeps `status` true to the callers
 * the repo actually has.
 */

export const CATALOG_CATEGORIES = [
  { id: "actions", title: "Actions" },
  { id: "forms", title: "Forms" },
  { id: "overlays", title: "Overlays" },
  { id: "navigation", title: "Navigation" },
  { id: "data-display", title: "Data display" },
  { id: "feedback", title: "Feedback" },
  { id: "layout", title: "Layout" },
  { id: "charts", title: "Charts & maps" },
  { id: "ai", title: "AI" },
  { id: "marketing", title: "Marketing" },
  { id: "media", title: "Media" },
  { id: "effects", title: "Backgrounds & effects" },
  { id: "text-motion", title: "Text & motion" },
] as const;

export type CatalogCategory = (typeof CATALOG_CATEGORIES)[number]["id"];

/**
 * stable       — at least one app or package outside @nebutra/ui imports it.
 * experimental — nothing outside the library uses it yet; shown, not promised.
 */
export type CatalogStatus = "stable" | "experimental";

export type CatalogImport =
  | "@nebutra/ui/primitives"
  | "@nebutra/ui/components"
  | "@nebutra/ui/patterns"
  | "@nebutra/ui/layout";

export interface CatalogEntry {
  /** kebab-case, unique; also the prefix of every demo id it owns */
  id: string;
  title: string;
  category: CatalogCategory;
  status: CatalogStatus;
  /** the entry point an app imports it from */
  import: CatalogImport;
  /** source files, relative to packages/design/ui/src */
  files: readonly string[];
  /** demo ids — files in ./demos — the first is the one a listing shows */
  demos: readonly string[];
}

/** Shared building blocks the entries are made of; not components in their own right. */
export const INTERNAL_FILES: readonly string[] = [
  "layout/DesignSystemProvider.tsx",
  "primitives/brand-mark.tsx",
  "primitives/canvas-reveal-effect.tsx",
  "primitives/control-glyph.tsx",
  "primitives/form-control.ts",
  "primitives/overlay.ts",
  // The labels contract (provider + defaults), not a component with a demo.
  "primitives/ui-labels.tsx",
];

export const CATALOG: readonly CatalogEntry[] = [
  {
    id: "button",
    title: "Button",
    category: "actions",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/button-variants.ts", "primitives/button.tsx"],
    demos: [
      "button-demo",
      "button-loading-demo",
      "button-sizes-demo",
      "button-variants-demo",
      "button-with-icon-demo",
    ],
  },
  {
    id: "copy-button",
    title: "Copy Button",
    category: "actions",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/copy-button.tsx"],
    demos: ["copy-button-demo"],
  },
  {
    id: "kbd",
    title: "Kbd",
    category: "actions",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/kbd.tsx"],
    demos: ["kbd-demo"],
  },
  {
    id: "split-button",
    title: "Split Button",
    category: "actions",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/split-button.tsx"],
    demos: ["split-button-demo"],
  },
  {
    id: "theme-switcher",
    title: "Theme Switcher",
    category: "actions",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/theme-switcher.tsx"],
    demos: ["theme-switcher-demo"],
  },
  {
    id: "theme-toggle",
    title: "Theme Toggle",
    category: "actions",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/theme-toggle.tsx"],
    demos: ["theme-toggle-demo"],
  },
  {
    id: "toggle",
    title: "Toggle",
    category: "actions",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/toggle.tsx"],
    demos: [
      "toggle-demo",
      "toggle-2-demo",
      "toggle-3-demo",
      "toggle-4-demo",
      "toggle-large-demo",
      "toggle-small-demo",
    ],
  },
  {
    id: "toggle-group",
    title: "Toggle Group",
    category: "actions",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/toggle-group-variants.ts", "primitives/toggle-group.tsx"],
    demos: [
      "toggle-group-demo",
      "toggle-group-2-demo",
      "toggle-group-3-demo",
      "toggle-group-single-demo",
    ],
  },
  {
    id: "assisted-password-confirmation",
    title: "Assisted Password Confirmation",
    category: "forms",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/assisted-password-confirmation.tsx"],
    demos: ["assisted-password-confirmation-demo"],
  },
  {
    id: "calendar",
    title: "Calendar",
    category: "forms",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/calendar.tsx"],
    demos: ["calendar-demo"],
  },
  {
    id: "checkbox",
    title: "Checkbox",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/checkbox-group.tsx"],
    demos: ["checkbox-demo", "checkbox-group-demo", "checkbox-indeterminate-demo"],
  },
  {
    id: "choicebox",
    title: "Choicebox",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/choicebox.tsx"],
    demos: ["choicebox-demo", "choicebox-radio-demo"],
  },
  {
    id: "combobox",
    title: "Combobox",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/combobox.tsx"],
    demos: [
      "combobox-demo",
      "combobox-10-demo",
      "combobox-11-demo",
      "combobox-2-demo",
      "combobox-3-demo",
      "combobox-4-demo",
      "combobox-5-demo",
      "combobox-6-demo",
      "combobox-7-demo",
      "combobox-8-demo",
      "combobox-9-demo",
      "combobox-default-value-demo",
      "combobox-disabled-demo",
      "combobox-error-demo",
      "combobox-groups-demo",
      "combobox-sizes-demo",
      "combobox-width-demo",
    ],
  },
  {
    id: "date-picker",
    title: "Date Picker",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/date-picker.tsx"],
    demos: ["date-picker-demo"],
  },
  {
    id: "error-message",
    title: "Error Message",
    category: "forms",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/error-message.tsx"],
    demos: ["error-message-demo"],
  },
  {
    id: "expanding-textarea",
    title: "Expanding Textarea",
    category: "forms",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/expanding-textarea.tsx"],
    demos: ["expanding-textarea-demo"],
  },
  {
    id: "feedback",
    title: "Feedback",
    category: "forms",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/feedback.tsx"],
    demos: ["feedback-demo"],
  },
  {
    id: "field",
    title: "Field",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/field.tsx"],
    demos: ["field-demo"],
  },
  {
    id: "filter-pills",
    title: "Filter Pills",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/filter-pills.tsx"],
    demos: ["filter-pills-demo"],
  },
  {
    id: "form",
    title: "Form",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/form.tsx"],
    demos: ["form-demo"],
  },
  {
    id: "number-field",
    title: "Number Field",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/number-field.tsx"],
    demos: ["number-field-demo"],
  },
  {
    id: "dropzone",
    title: "Dropzone",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/dropzone.tsx"],
    demos: ["dropzone-demo"],
  },
  {
    id: "input",
    title: "Input",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/input.tsx"],
    demos: [
      "input-demo",
      "input-2-demo",
      "input-basic-demo",
      "input-clearable-demo",
      "input-error-demo",
      "input-password-reveal-demo",
      "input-with-addons-demo",
      "input-with-icon-demo",
      "input-with-label-demo",
    ],
  },
  {
    id: "input-otp",
    title: "Input OTP",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/input-otp.tsx"],
    demos: ["input-otp-demo", "input-otp-numeric-demo"],
  },
  {
    id: "label",
    title: "Label",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/label.tsx"],
    demos: [
      "label-demo",
      "label-2-demo",
      "label-3-demo",
      "label-4-demo",
      "label-description-demo",
      "label-disabled-demo",
    ],
  },
  {
    id: "multiple-selector",
    title: "Multiple Selector",
    category: "forms",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/multiple-selector.tsx"],
    demos: ["multiple-selector-demo"],
  },
  {
    id: "radio-group",
    title: "Radio Group",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/radio-group.tsx"],
    demos: [
      "radio-group-demo",
      "radio-group-2-demo",
      "radio-group-3-demo",
      "radio-group-billing-demo",
      "radio-group-horizontal-demo",
    ],
  },
  {
    id: "radio-group-card",
    title: "Radio Group Card",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/radio-group-card.tsx"],
    demos: ["radio-group-card-demo"],
  },
  {
    id: "radio-group-stacked",
    title: "Radio Group Stacked",
    category: "forms",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/radio-group-stacked.tsx"],
    demos: ["radio-group-stacked-demo"],
  },
  {
    id: "select",
    title: "Select",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/select.tsx"],
    demos: ["select-demo", "select-disabled-demo", "select-groups-demo"],
  },
  {
    id: "color-picker",
    title: "Color Picker",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/color-math.ts", "primitives/color-picker.tsx"],
    demos: [
      "color-picker-demo",
      "color-picker-alpha-demo",
      "color-picker-popover-demo",
      "color-picker-swatches-demo",
    ],
  },
  {
    id: "slider",
    title: "Slider",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/slider.tsx"],
    demos: [
      "slider-demo",
      "slider-2-demo",
      "slider-3-demo",
      "slider-4-demo",
      "slider-icon-demo",
      "slider-on-value-change-demo",
      "slider-stateful-demo",
    ],
  },
  {
    id: "slider-number-flow",
    title: "Slider Number Flow",
    category: "forms",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/slider-number-flow.tsx"],
    demos: ["slider-number-flow-demo"],
  },
  {
    id: "switch",
    title: "Switch",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/switch.tsx"],
    demos: ["switch-demo"],
  },
  {
    id: "textarea",
    title: "Textarea",
    category: "forms",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/textarea.tsx"],
    demos: [
      "textarea-demo",
      "textarea-2-demo",
      "textarea-3-demo",
      "textarea-disabled-demo",
      "textarea-with-limit-demo",
    ],
  },
  {
    id: "alert-dialog",
    title: "Alert Dialog",
    category: "overlays",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/alert-dialog.tsx"],
    demos: ["alert-dialog-demo", "alert-dialog-custom-demo"],
  },
  {
    id: "command",
    title: "Command",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/command-styles.ts", "primitives/command.tsx"],
    demos: ["command-demo", "command-dialog-demo", "command-dialog-simple-demo"],
  },
  {
    id: "command-menu",
    title: "Command Menu",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/command-menu-parts.tsx", "primitives/command-menu.tsx"],
    demos: ["command-menu-demo"],
  },
  {
    id: "confirm-dialog",
    title: "Confirm Dialog",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/confirm-dialog.tsx", "primitives/use-confirm.tsx"],
    demos: ["confirm-dialog-demo", "confirm-dialog-use-confirm-demo"],
  },
  {
    id: "context-menu",
    title: "Context Menu",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/context-menu.tsx"],
    demos: ["context-menu-demo", "context-menu-with-icons-demo"],
  },
  {
    id: "dialog",
    title: "Dialog",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/dialog.tsx"],
    demos: [
      "dialog-demo",
      "dialog-deactivate-demo",
      "dialog-destructive-demo",
      "dialog-password-demo",
      "dialog-share-demo",
      "dialog-success-demo",
    ],
  },
  {
    id: "drawer",
    title: "Drawer",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/drawer.tsx"],
    demos: ["drawer-demo", "drawer-2-demo", "drawer-3-demo", "drawer-side-right-demo"],
  },
  {
    id: "dropdown-menu",
    title: "Dropdown Menu",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/dropdown-menu.tsx"],
    demos: [
      "dropdown-menu-demo",
      "dropdown-menu-2-demo",
      "dropdown-menu-3-demo",
      "dropdown-menu-4-demo",
      "dropdown-menu-5-demo",
      "dropdown-menu-6-demo",
      "dropdown-menu-7-demo",
      "dropdown-menu-8-demo",
      "dropdown-menu-9-demo",
      "dropdown-menu-radio-group-demo",
      "dropdown-menu-sub-demo",
    ],
  },
  {
    id: "hover-card",
    title: "Hover Card",
    category: "overlays",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: [
      "primitives/hover-card-content.tsx",
      "primitives/hover-card-trigger.tsx",
      "primitives/hover-card.tsx",
    ],
    demos: ["hover-card-demo", "hover-card-2-demo"],
  },
  {
    id: "menubar",
    title: "Menubar",
    category: "overlays",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/menubar.tsx"],
    demos: ["menubar-demo"],
  },
  {
    id: "popover",
    title: "Popover",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/popover.tsx"],
    demos: ["popover-demo", "popover-2-demo", "popover-controlled-demo", "popover-settings-demo"],
  },
  {
    id: "sheet",
    title: "Sheet",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/sheet.tsx"],
    demos: ["sheet-demo", "sheet-mobile-demo", "sheet-side-demo"],
  },
  {
    id: "tooltip",
    title: "Tooltip",
    category: "overlays",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/tooltip.tsx"],
    demos: [
      "tooltip-demo",
      "tooltip-icon-button-demo",
      "tooltip-instant-demo",
      "tooltip-rich-content-demo",
      "tooltip-side-right-demo",
    ],
  },
  {
    id: "breadcrumb",
    title: "Breadcrumb",
    category: "navigation",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/breadcrumb.tsx"],
    demos: ["breadcrumb-demo", "breadcrumb-custom-separator-demo", "breadcrumb-ellipsis-demo"],
  },
  {
    id: "dynamic-island-toc",
    title: "Dynamic Island TOC",
    category: "navigation",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/dynamic-island-toc.tsx"],
    demos: ["dynamic-island-toc-demo"],
  },
  {
    id: "expandable-tabs",
    title: "Expandable Tabs",
    category: "navigation",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/expandable-tabs.tsx"],
    demos: ["expandable-tabs-demo"],
  },
  {
    id: "navigation-menu",
    title: "Navigation Menu",
    category: "navigation",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/navigation-menu-variants.ts", "primitives/navigation-menu.tsx"],
    demos: ["navigation-menu-demo"],
  },
  {
    id: "pagination",
    title: "Pagination",
    category: "navigation",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/pagination.tsx"],
    demos: ["pagination-demo"],
  },
  {
    id: "consent-card",
    title: "Consent Card",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/patterns",
    files: ["patterns/consent-card.tsx"],
    demos: ["consent-card-demo"],
  },
  {
    id: "sidebar-nav",
    title: "Sidebar Nav",
    category: "navigation",
    status: "stable",
    import: "@nebutra/ui/patterns",
    files: ["patterns/sidebar-nav/index.ts", "patterns/sidebar-nav/sidebar-nav.tsx"],
    demos: ["sidebar-nav-demo"],
  },
  {
    id: "stepper",
    title: "Stepper",
    category: "navigation",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/stepper.tsx"],
    demos: ["stepper-demo"],
  },
  {
    id: "tabs",
    title: "Tabs",
    category: "navigation",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/tabs.tsx"],
    demos: ["tabs-demo", "tabs-button-demo", "tabs-line-demo", "tabs-pill-demo"],
  },
  {
    id: "user-menu",
    title: "User Menu",
    category: "navigation",
    status: "experimental",
    import: "@nebutra/ui/patterns",
    files: ["patterns/user-menu.tsx"],
    demos: ["user-menu-demo"],
  },
  {
    id: "workspace-switcher",
    title: "Workspace Switcher",
    category: "navigation",
    status: "stable",
    import: "@nebutra/ui/patterns",
    files: ["patterns/workspace-switcher.tsx"],
    demos: ["workspace-switcher-demo"],
  },
  {
    id: "accordion",
    title: "Accordion",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/accordion.tsx"],
    demos: [
      "accordion-demo",
      "accordion-compact-demo",
      "accordion-controlled-demo",
      "accordion-disabled-demo",
    ],
  },
  {
    id: "avatar",
    title: "Avatar",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/avatar-extended.tsx", "primitives/avatar.tsx"],
    demos: [
      "avatar-demo",
      "avatar-dicebear-demo",
      "avatar-fallback-demo",
      "avatar-git-platform-demo",
      "avatar-group-demo",
      "avatar-with-icon-demo",
    ],
  },
  {
    id: "avatar-circles",
    title: "Avatar Circles",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/avatar-circles.tsx"],
    demos: ["avatar-circles-demo"],
  },
  {
    id: "avatar-smart-group",
    title: "Avatar Smart Group",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/avatar-smart-group.tsx"],
    demos: ["avatar-smart-group-demo"],
  },
  {
    id: "badge",
    title: "Badge",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/badge.tsx"],
    demos: [
      "badge-demo",
      "badge-feature-tag-demo",
      "badge-icon-colors-demo",
      "badge-icon-demo",
      "badge-notification-demo",
      "badge-pill-demo",
      "badge-pill-matrix-demo",
      "badge-sizes-demo",
      "badge-status-dot-demo",
      "badge-table-demo",
      "badge-variants-demo",
    ],
  },
  {
    id: "card",
    title: "Card",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: [
      "layout/Card.tsx",
      "patterns/Card/Card.tsx",
      "patterns/Card/index.ts",
      "primitives/card.tsx",
    ],
    demos: ["card-demo", "card-2-demo", "card-pricing-demo", "card-with-icon-demo"],
  },
  {
    id: "code-block",
    title: "Code Block",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/code-block-language-icon.tsx", "primitives/code-block.tsx"],
    demos: ["code-block-demo", "code-block-mermaid-demo"],
  },
  {
    id: "collapsible",
    title: "Collapsible",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/collapsible.tsx"],
    demos: ["collapsible-demo", "collapsible-2-demo"],
  },
  {
    id: "color-badge",
    title: "Color Badge",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/color-badge.tsx"],
    demos: ["color-badge-demo"],
  },
  {
    id: "context-card",
    title: "Context Card",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/context-card.tsx"],
    demos: ["context-card-demo"],
  },
  {
    id: "data-list",
    title: "Data List",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/data-list.tsx"],
    demos: ["data-list-demo"],
  },
  {
    id: "data-table",
    title: "Data Table",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/patterns",
    files: [
      "patterns/data-table/components/data-table-faceted-filter.tsx",
      "patterns/data-table/components/data-table-row.tsx",
      "patterns/data-table/components/data-table-toolbar.tsx",
      "patterns/data-table/data-table.tsx",
      "patterns/data-table/hooks/use-cell-selection.ts",
      "patterns/data-table/hooks/use-data-table.ts",
      "patterns/data-table/index.ts",
      "patterns/data-table/labels.ts",
      "patterns/data-table/types.ts",
      "patterns/data-table/utils.ts",
    ],
    demos: ["data-table-demo"],
  },
  {
    id: "description",
    title: "Description",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/description.tsx"],
    demos: ["description-demo"],
  },
  {
    id: "entity",
    title: "Entity",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/entity.tsx"],
    demos: ["entity-demo"],
  },
  {
    id: "file-attachment",
    title: "File Attachment",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/file-attachment.tsx"],
    demos: ["file-attachment-demo"],
  },
  {
    id: "file-card",
    title: "File Card",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/file-card.tsx"],
    demos: ["file-card-demo"],
  },
  {
    id: "folder",
    title: "Folder",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/folder.tsx"],
    demos: ["folder-demo"],
  },
  {
    id: "github-inline-diff",
    title: "Github Inline Diff",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/github-inline-diff.tsx"],
    demos: ["github-inline-diff-demo"],
  },
  {
    id: "heading",
    title: "Heading",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/heading.tsx"],
    demos: ["heading-demo"],
  },
  {
    id: "kpi-card",
    title: "KPI Card",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/kpi-card.tsx"],
    demos: ["kpi-card-demo"],
  },
  {
    id: "metric-card",
    title: "Metric Card",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/metric-card.tsx"],
    demos: ["metric-card-demo"],
  },
  {
    id: "middle-truncate",
    title: "Middle Truncate",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/middle-truncate.tsx"],
    demos: ["middle-truncate-demo"],
  },
  {
    id: "notification-message-list",
    title: "Notification Message List",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/notification-message-list.tsx"],
    demos: ["notification-message-list-demo"],
  },
  {
    id: "project-banner",
    title: "Project Banner",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/project-banner.tsx"],
    demos: ["project-banner-demo"],
  },
  {
    id: "reaction-chip",
    title: "Reaction Chip",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/reaction-chip.tsx"],
    demos: ["reaction-chip-demo", "reaction-chip-message-demo"],
  },
  {
    id: "relative-time-card",
    title: "Relative Time Card",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/relative-time-card.tsx"],
    demos: ["relative-time-card-demo"],
  },
  {
    id: "show-more",
    title: "Show More",
    category: "data-display",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/show-more.tsx"],
    demos: ["show-more-demo"],
  },
  {
    id: "status-badge",
    title: "Status Badge",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/status-badge.tsx"],
    demos: ["status-badge-demo"],
  },
  {
    id: "status-dot",
    title: "Status Dot",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/status-dot.tsx"],
    demos: ["status-dot-demo"],
  },
  {
    id: "table",
    title: "Table",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/table.tsx"],
    demos: ["table-demo"],
  },
  {
    id: "text",
    title: "Text",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/text.tsx"],
    demos: ["text-demo"],
  },
  {
    id: "tree",
    title: "Tree",
    category: "data-display",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/tree.tsx"],
    demos: ["tree-view-demo"],
  },
  {
    id: "alert",
    title: "Alert",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/alert.tsx"],
    demos: ["alert-demo", "alert-info-demo"],
  },
  {
    id: "animated-circular-progress-bar",
    title: "Animated Circular Progress Bar",
    category: "feedback",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/animated-circular-progress-bar.tsx"],
    demos: ["animated-circular-progress-bar-demo"],
  },
  {
    id: "empty-state",
    title: "Empty State",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["layout/EmptyState.tsx", "primitives/empty-state.tsx"],
    demos: ["empty-state-demo"],
  },
  {
    id: "error-state",
    title: "Error State",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/layout",
    files: ["layout/ErrorState.tsx"],
    demos: ["error-state-demo"],
  },
  {
    id: "full-page-status",
    title: "Full Page Status",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/layout",
    files: ["layout/FullPageStatus.tsx"],
    demos: ["full-page-status-demo"],
  },
  {
    id: "gauge",
    title: "Gauge",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/gauge.tsx"],
    demos: ["gauge-demo"],
  },
  {
    id: "loading-dots",
    title: "Loading Dots",
    category: "feedback",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/loading-dots.tsx"],
    demos: ["loading-dots-demo"],
  },
  {
    id: "loading-state",
    title: "Loading State",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/layout",
    files: ["layout/LoadingState.tsx"],
    demos: ["loading-state-demo"],
  },
  {
    id: "progress",
    title: "Progress",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/progress.tsx"],
    demos: [
      "progress-demo",
      "progress-2-demo",
      "progress-3-demo",
      "progress-4-demo",
      "progress-basic-demo",
      "progress-custom-color-demo",
      "progress-indeterminate-demo",
      "progress-with-label-demo",
    ],
  },
  {
    id: "skeleton",
    title: "Skeleton",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/skeleton.tsx"],
    demos: ["skeleton-demo", "skeleton-2-demo", "skeleton-3-demo", "skeleton-list-demo"],
  },
  {
    id: "spinner",
    title: "Spinner",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/spinner.tsx"],
    demos: ["spinner-demo"],
  },
  {
    id: "toaster",
    title: "Toaster",
    category: "feedback",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/toaster.tsx"],
    demos: ["toaster-demo"],
  },
  {
    id: "app-shell",
    title: "App Shell",
    category: "layout",
    status: "stable",
    import: "@nebutra/ui/layout",
    files: ["layout/app-shell.tsx"],
    demos: ["app-shell-demo"],
  },
  {
    id: "aspect-ratio",
    title: "Aspect Ratio",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/aspect-ratio.tsx"],
    demos: ["aspect-ratio-demo"],
  },
  {
    id: "bento-grid",
    title: "Bento Grid",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/bento-grid.tsx"],
    demos: ["bento-grid-demo"],
  },
  {
    id: "box",
    title: "Box",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/box.tsx"],
    demos: ["box-demo"],
  },
  {
    id: "carousel",
    title: "Carousel",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/carousel.tsx"],
    demos: [
      "carousel-demo",
      "carousel-2-demo",
      "carousel-3-demo",
      "carousel-multiple-demo",
      "carousel-vertical-demo",
    ],
  },
  {
    id: "flex",
    title: "Flex",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/flex.tsx"],
    demos: ["flex-demo"],
  },
  {
    id: "grid-system",
    title: "Grid System",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/grid-system.tsx"],
    demos: ["grid-system-demo"],
  },
  {
    id: "page-header",
    title: "Page Header",
    category: "layout",
    status: "stable",
    import: "@nebutra/ui/layout",
    files: ["layout/PageHeader.tsx"],
    demos: ["page-header-demo"],
  },
  {
    id: "resizable",
    title: "Resizable",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/resizable.tsx"],
    demos: ["resizable-demo", "resizable-2-demo"],
  },
  {
    id: "scroller",
    title: "Scroller",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/scroller.tsx"],
    demos: ["scroller-demo"],
  },
  {
    id: "section",
    title: "Section",
    category: "layout",
    status: "stable",
    import: "@nebutra/ui/layout",
    files: ["layout/Section.tsx"],
    demos: ["section-demo"],
  },
  {
    id: "section-container",
    title: "Section Container",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/layout",
    files: ["layout/SectionContainer.tsx"],
    demos: ["section-container-demo"],
  },
  {
    id: "separator",
    title: "Separator",
    category: "layout",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/separator.tsx"],
    demos: [
      "separator-demo",
      "separator-2-demo",
      "separator-3-demo",
      "separator-4-demo",
      "separator-vertical-demo",
      "separator-with-text-demo",
      "separator-with-text-i18n-demo",
    ],
  },
  {
    id: "stack",
    title: "Stack",
    category: "layout",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/stack.tsx"],
    demos: ["stack-demo"],
  },
  {
    id: "chart",
    title: "Chart",
    category: "charts",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/chart.tsx"],
    demos: ["chart-demo"],
  },
  {
    id: "dotted-map",
    title: "Dotted Map",
    category: "charts",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/dotted-map.tsx"],
    demos: ["dotted-map-demo"],
  },
  {
    id: "github-calendar",
    title: "Github Calendar",
    category: "charts",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/github-calendar-data.ts", "primitives/github-calendar.tsx"],
    demos: ["github-calendar-demo"],
  },
  {
    id: "agent-plan",
    title: "Agent Plan",
    category: "ai",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/agent-plan.tsx"],
    demos: ["agent-plan-demo"],
  },
  {
    id: "edit-tool",
    title: "Edit Tool",
    category: "ai",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/edit-tool.tsx"],
    demos: ["edit-tool-demo"],
  },
  {
    id: "mcp-tool",
    title: "MCP Tool",
    category: "ai",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/mcp-tool.tsx"],
    demos: ["mcp-tool-demo"],
  },
  {
    id: "message-content",
    title: "Message Content",
    category: "ai",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/message-content.tsx"],
    demos: ["message-content-demo"],
  },
  {
    id: "node-graph-canvas",
    title: "Node Graph Canvas",
    category: "ai",
    status: "stable",
    import: "@nebutra/ui/components",
    files: ["components/node-graph-canvas-adapter.ts", "components/node-graph-canvas.tsx"],
    demos: ["node-graph-canvas-demo"],
  },
  {
    id: "prompt-input",
    title: "Prompt Input",
    category: "ai",
    status: "stable",
    import: "@nebutra/ui/components",
    files: [
      "components/ai-prompt-box.tsx",
      "components/ai-prompt-box/file-attachment-zone.tsx",
      "components/ai-prompt-box/prompt-input.tsx",
      "components/ai-prompt-box/voice-visualizer.tsx",
    ],
    demos: ["prompt-input-demo"],
  },
  {
    id: "question-tool",
    title: "Question Tool",
    category: "ai",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/question-tool.tsx"],
    demos: ["question-tool-demo"],
  },
  {
    id: "search-tool",
    title: "Search Tool",
    category: "ai",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/search-tool.tsx"],
    demos: ["search-tool-demo"],
  },
  {
    id: "subagent-tool",
    title: "Subagent Tool",
    category: "ai",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/subagent-tool.tsx"],
    demos: ["subagent-tool-demo"],
  },
  {
    id: "terminal",
    title: "Terminal",
    category: "ai",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/terminal.tsx"],
    demos: ["terminal-demo"],
  },
  {
    id: "todo-tool",
    title: "Todo Tool",
    category: "ai",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/todo-tool.tsx"],
    demos: ["todo-tool-demo"],
  },
  {
    id: "animated-hike-card",
    title: "Animated Hike Card",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/animated-hike-card.tsx"],
    demos: ["animated-hike-card-demo"],
  },
  {
    id: "announcement",
    title: "Announcement",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/announcement.tsx"],
    demos: ["announcement-demo"],
  },
  {
    id: "artifact-shift-card",
    title: "Artifact Shift Card",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/patterns",
    files: ["patterns/artifact-shift-card.tsx"],
    demos: ["artifact-shift-card-demo"],
  },
  {
    id: "awards",
    title: "Awards",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/awards.tsx"],
    demos: ["awards-demo"],
  },
  {
    id: "card-spotlight",
    title: "Card Spotlight",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/card-spotlight.tsx"],
    demos: ["card-spotlight-demo"],
  },
  {
    id: "dashboard-surfaces",
    title: "Dashboard Surfaces",
    category: "marketing",
    status: "stable",
    import: "@nebutra/ui/patterns",
    files: ["patterns/dashboard-surfaces.tsx"],
    demos: ["dashboard-surfaces-demo"],
  },
  {
    id: "feature-card",
    title: "Feature Card",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/feature-card.tsx"],
    demos: ["feature-card-demo"],
  },
  {
    id: "feature-check-item",
    title: "Feature Check Item",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/feature-check-item.tsx"],
    demos: ["feature-check-item-demo"],
  },
  {
    id: "feature-icon-item",
    title: "Feature Icon Item",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/feature-icon-item.tsx"],
    demos: ["feature-icon-item-demo"],
  },
  {
    id: "gallery-card",
    title: "Gallery Card",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/patterns",
    files: ["patterns/gallery-card.tsx"],
    demos: ["gallery-card-demo"],
  },
  {
    id: "grid-feature-card",
    title: "Grid Feature Card",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/grid-feature-card.tsx"],
    demos: ["grid-feature-card-demo"],
  },
  {
    id: "infinite-slider",
    title: "Infinite Slider",
    category: "marketing",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/infinite-slider.tsx"],
    demos: ["infinite-slider-demo"],
  },
  {
    id: "kinetic-marketing",
    title: "Kinetic Marketing",
    category: "marketing",
    status: "stable",
    import: "@nebutra/ui/patterns",
    files: ["patterns/kinetic-marketing.tsx"],
    demos: ["kinetic-marketing-demo"],
  },
  {
    id: "magic-card",
    title: "Magic Card",
    category: "marketing",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/magic-card.tsx"],
    demos: ["magic-card-demo"],
  },
  {
    id: "pricing-card",
    title: "Pricing Card",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/pricing-card.tsx"],
    demos: ["pricing-card-demo"],
  },
  {
    id: "scroll-velocity",
    title: "Scroll Velocity",
    category: "marketing",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/scroll-velocity.tsx"],
    demos: ["scroll-velocity-demo"],
  },
  {
    id: "book",
    title: "Book",
    category: "media",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/book.tsx"],
    demos: ["book-demo"],
  },
  {
    id: "macbook-pro",
    title: "MacBook Pro",
    category: "media",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/macbook-pro.tsx"],
    demos: ["macbook-pro-demo"],
  },
  {
    id: "animated-beam",
    title: "Animated Beam",
    category: "effects",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/animated-beam.tsx"],
    demos: ["animated-beam-demo"],
  },
  {
    id: "aurora-background",
    title: "Aurora Background",
    category: "effects",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/aurora-background.tsx"],
    demos: ["aurora-background-demo"],
  },
  {
    id: "border-trail",
    title: "Border Trail",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/border-trail.tsx"],
    demos: ["border-trail-demo"],
  },
  {
    id: "confetti",
    title: "Confetti",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/confetti.tsx"],
    demos: ["confetti-demo"],
  },
  {
    id: "dithering-background",
    title: "Dithering Background",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/dithering-background.tsx"],
    demos: ["dithering-background-demo"],
  },
  {
    id: "dot-pattern",
    title: "Dot Pattern",
    category: "effects",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/dot-pattern.tsx"],
    demos: ["dot-pattern-demo"],
  },
  {
    id: "flickering-grid",
    title: "Flickering Grid",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/flickering-grid.tsx"],
    demos: ["flickering-grid-demo"],
  },
  {
    id: "grain-gradient-background",
    title: "Grain Gradient Background",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/grain-gradient-background.tsx"],
    demos: ["grain-gradient-background-demo"],
  },
  {
    id: "grid-pattern-card",
    title: "Grid Pattern Card",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/grid-pattern-card.tsx"],
    demos: ["grid-pattern-card-demo"],
  },
  {
    id: "hex-grid",
    title: "Hex Grid",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/hex-grid.tsx"],
    demos: ["hex-grid-demo"],
  },
  {
    id: "light-rays",
    title: "Light Rays",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/light-rays.tsx"],
    demos: ["light-rays-demo"],
  },
  {
    id: "material",
    title: "Material",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/material.tsx"],
    demos: ["material-demo"],
  },
  {
    id: "noise-pattern-card",
    title: "Noise Pattern Card",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/noise-pattern-card.tsx"],
    demos: ["noise-pattern-card-demo"],
  },
  {
    id: "progressive-blur",
    title: "Progressive Blur",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/progressive-blur.tsx"],
    demos: ["progressive-blur-demo"],
  },
  {
    id: "shine-border",
    title: "Shine Border",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/shine-border.tsx"],
    demos: ["shine-border-demo"],
  },
  {
    id: "stars-canvas",
    title: "Stars Canvas",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/stars-canvas.tsx"],
    demos: ["stars-canvas-demo"],
  },
  {
    id: "warp-background",
    title: "Warp Background",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/warp-background.tsx"],
    demos: ["warp-background-demo"],
  },
  {
    id: "wave-animation",
    title: "Wave Animation",
    category: "effects",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/wave-animation.tsx"],
    demos: ["wave-animation-demo"],
  },
  {
    id: "animate-in",
    title: "Animate In",
    category: "text-motion",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["components/animate-in.tsx", "primitives/animate-in.tsx"],
    demos: ["animate-in-demo"],
  },
  {
    id: "animated-gradient-text",
    title: "Animated Gradient Text",
    category: "text-motion",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/animated-gradient-text.tsx"],
    demos: ["animated-gradient-text-demo"],
  },
  {
    id: "animated-group",
    title: "Animated Group",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/animated-group.tsx"],
    demos: ["animated-group-demo"],
  },
  {
    id: "animated-list",
    title: "Animated List",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/animated-list.tsx"],
    demos: ["animated-list-demo"],
  },
  {
    id: "animated-shiny-text",
    title: "Animated Shiny Text",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/animated-shiny-text.tsx"],
    demos: ["animated-shiny-text-demo"],
  },
  {
    id: "aurora-text",
    title: "Aurora Text",
    category: "text-motion",
    status: "stable",
    import: "@nebutra/ui/primitives",
    files: ["primitives/aurora-text.tsx"],
    demos: ["aurora-text-demo"],
  },
  {
    id: "gradient-animated-text",
    title: "Gradient Animated Text",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/gradient-animated-text.tsx"],
    demos: ["gradient-animated-text-demo"],
  },
  {
    id: "highlighter",
    title: "Highlighter",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/highlighter.tsx"],
    demos: ["highlighter-demo"],
  },
  {
    id: "line-shadow-text",
    title: "Line Shadow Text",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/line-shadow-text.tsx"],
    demos: ["line-shadow-text-demo"],
  },
  {
    id: "text-loop",
    title: "Text Loop",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/text-loop.tsx"],
    demos: ["text-loop-demo"],
  },
  {
    id: "text-scramble",
    title: "Text Scramble",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/text-scramble.tsx"],
    demos: ["text-scramble-demo"],
  },
  {
    id: "text-shimmer",
    title: "Text Shimmer",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/text-shimmer.tsx"],
    demos: ["text-shimmer-demo"],
  },
  {
    id: "word-fade-in",
    title: "Word Fade In",
    category: "text-motion",
    status: "experimental",
    import: "@nebutra/ui/primitives",
    files: ["primitives/word-fade-in.tsx"],
    demos: ["word-fade-in-demo"],
  },
];
