#!/usr/bin/env node
/**
 * Writes src/catalog/demo-loaders.generated.ts: one lazy loader per demo in
 * src/catalog/demos, each a literal import() so every bundler can split it.
 * (A template-literal import across a package `exports` map resolves to
 * nothing under webpack — that is how the old docs preview registry broke.)
 *
 *   node scripts/gen-catalog.mjs          write
 *   node scripts/gen-catalog.mjs --check  exit 1 when the file is stale
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const demosDir = join(root, "src/catalog/demos");
const outFile = join(root, "src/catalog/demo-loaders.generated.ts");

/** The one component a demo file exports: `{ name, isDefault }`. */
export function demoExport(source, file) {
  // Code shown inside a demo lives in template literals; it is not an export.
  const code = source.replace(/`[\s\S]*?`/g, "``");
  const found = [
    ...code.matchAll(/^export\s+(default\s+)?function\s+([A-Z]\w*)/gm),
    ...code.matchAll(/^export\s+(default\s+)?const\s+([A-Z]\w*)/gm),
  ];
  if (found.length !== 1) {
    throw new Error(`${file}: a demo exports exactly one component, found ${found.length}`);
  }
  return { name: found[0][2], isDefault: Boolean(found[0][1]) };
}

export function renderLoaders() {
  const lines = [
    "// GENERATED by scripts/gen-catalog.mjs — do not edit. Run `pnpm --filter @nebutra/ui gen:catalog`.",
    'import type { ComponentType } from "react";',
    "",
    "/** The named export a demo module carries (modules are typed `unknown`: demo-modules.d.ts). */",
    "const pick = (name: string) => (module: unknown) =>",
    "  (module as Record<string, ComponentType>)[name] as ComponentType;",
    "",
    "export const DEMO_LOADERS: Readonly<Record<string, () => Promise<ComponentType>>> = {",
  ];
  for (const file of readdirSync(demosDir)
    .filter((f) => f.endsWith(".tsx"))
    .sort()) {
    const id = file.slice(0, -4);
    const { name, isDefault } = demoExport(readFileSync(join(demosDir, file), "utf8"), file);
    const exported = isDefault ? "default" : name;
    lines.push(
      `  "${id}": () => import("@nebutra/ui/catalog/demos/${id}").then(pick("${exported}")),`,
    );
  }
  lines.push("};", "");
  return lines.join("\n");
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const next = renderLoaders();
  if (process.argv.includes("--check")) {
    const current = readFileSync(outFile, "utf8");
    if (current !== next) {
      console.error(
        "demo-loaders.generated.ts is stale. Run `pnpm --filter @nebutra/ui gen:catalog`.",
      );
      process.exit(1);
    }
  } else {
    writeFileSync(outFile, next);
  }
}
