import type { Meta, StoryObj } from "@storybook/react";
import { expect, userEvent, within } from "@storybook/test";
import { useState } from "react";
import { Textarea, type TextareaProps } from "./textarea";

const meta = {
  title: "Primitives/Textarea",
  component: Textarea,
  parameters: {
    layout: "centered",
    docs: {
      description: {
        component:
          "Token-driven multi-line text input. Supports labelled usage, helper/error text, compact sizing, and native textarea behavior without leaking browser focus outlines.",
      },
    },
  },
  tags: ["autodocs"],
  argTypes: {
    size: {
      control: "select",
      options: ["sm", "md", "lg"],
    },
    rows: { control: "number" },
    placeholder: { control: "text" },
    disabled: { control: "boolean" },
    readOnly: { control: "boolean" },
  },
  decorators: [
    (Story) => (
      <div className="w-[420px] max-w-[calc(100vw-2rem)]">
        <Story />
      </div>
    ),
  ],
} satisfies Meta<TextareaProps>;

export default meta;
type Story = StoryObj<TextareaProps>;
type PlayContext = {
  canvasElement: HTMLElement;
};

function CharacterCountDemo() {
  const [value, setValue] = useState("");
  const maxLength = 500;

  return (
    <div className="grid gap-1">
      <Textarea
        id="release-notes"
        label="Release Notes"
        maxLength={maxLength}
        onValueChange={setValue}
        placeholder="Summarize user-facing changes."
        rows={4}
      />
      <p className="text-right text-muted-foreground text-xs">
        {value.length}/{maxLength}
      </p>
    </div>
  );
}

export const Default: Story = {
  args: {
    "aria-label": "Message",
    placeholder: "Write your message here...",
    rows: 4,
  },
  play: async ({ canvasElement }: PlayContext) => {
    const canvas = within(canvasElement);
    const textarea = canvas.getByRole("textbox", { name: "Message" });

    await userEvent.click(textarea);
    await userEvent.type(textarea, "Ship the fix behind the existing form token contract.");

    expect(textarea).toHaveValue("Ship the fix behind the existing form token contract.");
  },
};

export const AllSizes: Story = {
  render: () => (
    <div className="grid gap-3">
      <Textarea aria-label="Small notes" size="sm" placeholder="Small" rows={3} />
      <Textarea aria-label="Default notes" placeholder="Default" rows={3} />
      <Textarea aria-label="Large notes" size="lg" placeholder="Large" rows={3} />
    </div>
  ),
};

export const WithLabelAndDescription: Story = {
  render: () => (
    <Textarea
      id="description"
      label="Description"
      description="Use one clear sentence before adding implementation details."
      placeholder="Customers can now..."
      rows={4}
    />
  ),
  play: async ({ canvasElement }: PlayContext) => {
    const canvas = within(canvasElement);
    const textarea = canvas.getByLabelText("Description");

    expect(textarea).toHaveAccessibleDescription(
      "Use one clear sentence before adding implementation details.",
    );
  },
};

export const ErrorState: Story = {
  render: () => (
    <Textarea
      id="incident-summary"
      label="Incident Summary"
      defaultValue="It broke."
      error="Incident summary must name the affected surface."
      rows={4}
    />
  ),
  play: async ({ canvasElement }: PlayContext) => {
    const canvas = within(canvasElement);
    const textarea = canvas.getByLabelText("Incident Summary");

    expect(textarea).toHaveAttribute("aria-invalid", "true");
    expect(canvas.getByRole("alert")).toHaveTextContent(
      "Incident summary must name the affected surface.",
    );
  },
};

export const DisabledAndReadOnly: Story = {
  render: () => (
    <div className="grid gap-3">
      <Textarea aria-label="Disabled placeholder" disabled placeholder="Disabled textarea" />
      <Textarea
        aria-label="Read-only audit note"
        readOnly
        value="Generated by the audit pipeline."
      />
    </div>
  ),
};

export const LongText: Story = {
  args: {
    "aria-label": "Long deployment notes",
    defaultValue:
      "This deployment touches form primitives, documentation previews, and governance checks. The textarea should preserve readable line height, stable padding, tokenized focus rings, and predictable wrapping for long user-authored content without clipping the resize affordance.",
    rows: 6,
  },
};

export const Empty: Story = {
  render: () => (
    <Textarea
      id="empty-feedback"
      label="Feedback"
      description="Optional, but useful when the selected rating needs context."
      placeholder="No feedback yet."
      rows={4}
    />
  ),
};

export const Loading: Story = {
  render: () => (
    <Textarea
      id="generated-summary"
      label="Generated Summary"
      value="Generating a draft summary..."
      readOnly
      aria-busy="true"
      description="The field remains readable while async generation is in progress."
      rows={4}
    />
  ),
};

export const CharacterCount: Story = {
  render: () => <CharacterCountDemo />,
};

export const DarkMode: Story = {
  render: () => (
    <div className="dark rounded-[var(--radius-lg)] bg-background p-6">
      <Textarea
        id="dark-release-notes"
        label="Release Notes"
        placeholder="Write dark-mode safe notes."
        rows={4}
      />
    </div>
  ),
};
